apiVersion: db.example.io/v1alpha1
kind: DatabaseBackup
metadata:
  name: postgres-daily-backup
  namespace: default
spec:
  databaseType: postgres
  schedule: "0 1 * * *"  # Daily at 1 AM
  backupRetention: 336   # 14 days (in hours)
  storageDestination:
    type: s3
    bucket: my-database-backups
    path: postgres/daily
    secretName: s3-credentials
  databaseSelector:
    matchLabels:
      app: postgres
      role: primary
